{"name": "Проверка появления ошибки при заполнении невалидного логина/пароля и возвращения правильного код ответа", "status": "passed", "attachments": [{"name": "stdout", "source": "c0bb2e37-5050-4d41-a49b-5e7598cbf62b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "['frersljdhu', 'xphjoulomo', 'lwmuyuhorm']"}, {"name": "password", "value": "'123456'"}], "start": 1706729778920, "stop": 1706729779268, "uuid": "0540a44c-cac6-4368-9aef-682d9249278b", "historyId": "0990eb240fbec882ac032a5b024c7ef4", "testCaseId": "1948f0443281776f830c6ca14962e75a", "fullName": "tests.test_courier_auth.TestAuth#test_return_error_message_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "MacBook-Air-Kamilla.local"}, {"name": "thread", "value": "14573-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}