{"name": "Проверка появления ошибки при заполнении невалидного логина/пароля и возвращения правильного код ответа", "status": "passed", "attachments": [{"name": "stdout", "source": "95627ae7-439d-4761-9e4e-869eb86e0666-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "'yytr'"}, {"name": "password", "value": "['brjemwnvrt', 'zrfjgysqju', 'arytzljczc']"}], "start": 1706729778553, "stop": 1706729778916, "uuid": "3de411ff-ba48-4a12-a2bd-a970b1890fd1", "historyId": "d3e0cac8bcafad1c4f098d6bc546fcd0", "testCaseId": "1948f0443281776f830c6ca14962e75a", "fullName": "tests.test_courier_auth.TestAuth#test_return_error_message_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "MacBook-Air-Kamilla.local"}, {"name": "thread", "value": "14573-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}